// Vendor dev-only npm packages into assets/ so the shipped site is fully offline.
// Run: node tools/vendor-assets.mjs   (or npm run assets)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const nm = path.join(root, 'node_modules');
const ensure = (p) => fs.mkdirSync(p, { recursive: true });
const copy = (from, to) => { ensure(path.dirname(to)); fs.copyFileSync(from, to); };

// ── 1. Fonts ─────────────────────────────────────────────────
const fontOut = path.join(root, 'assets/fonts');
ensure(fontOut);
const families = [
  {
    family: 'Inter', slug: 'inter', dir: '@fontsource/inter',
    weights: [400, 500, 600, 700, 800], style: 'normal',
  },
  {
    family: 'JetBrains Mono', slug: 'jetbrains-mono', dir: '@fontsource/jetbrains-mono',
    weights: [400, 500, 700], style: 'normal',
  },
];
let faceCss = '/* Generated by tools/vendor-assets.mjs — do not edit */\n';
for (const f of families) {
  for (const w of f.weights) {
    const file = `${f.slug}-latin-${w}-${f.style}.woff2`;
    const src = path.join(nm, f.dir, 'files', file);
    if (!fs.existsSync(src)) { console.warn('missing font', file); continue; }
    copy(src, path.join(fontOut, file));
    faceCss += `@font-face{font-family:'${f.family}';font-style:${f.style};font-weight:${w};font-display:swap;src:url('./${file}') format('woff2');}\n`;
  }
}
fs.writeFileSync(path.join(fontOut, 'fonts.css'), faceCss);

// ── 2. Prism syntax highlighter (single bundle) ──────────────
const prismOut = path.join(root, 'assets/js/vendor');
ensure(prismOut);
const order = ['prism-core', 'prism-clike', 'prism-markup', 'prism-css', 'prism-javascript', 'prism-sql', 'prism-bash', 'prism-yaml', 'prism-powershell', 'prism-json'];
let prism = '/* PrismJS bundled by tools/vendor-assets.mjs (MIT) */\n';
for (const c of order) {
  const src = path.join(nm, 'prismjs/components', `${c}.min.js`);
  if (!fs.existsSync(src)) { console.warn('missing prism', c); continue; }
  prism += fs.readFileSync(src, 'utf8') + '\n';
}
fs.writeFileSync(path.join(prismOut, 'prism-bundle.js'), prism);

// ── 3. Lucide icon sprite ────────────────────────────────────
const ICONS = [
  // levels
  'rocket', 'wrench', 'flame', 'crown',
  // topic icons
  'compass', 'package', 'blocks', 'hammer', 'sprout', 'circle-check', 'box', 'puzzle',
  'flask-conical', 'history', 'refresh-cw', 'zap', 'chart-line', 'satellite', 'settings',
  'bot', 'gauge', 'dna', 'sliders-horizontal', 'landmark',
  // ui
  'sun', 'moon', 'search', 'menu', 'x', 'arrow-left', 'arrow-right', 'copy', 'check',
  'info', 'triangle-alert', 'lightbulb', 'book-open', 'layers', 'terminal', 'external-link',
  'chevron-down', 'chevron-right', 'circle-help', 'sparkles', 'database', 'table', 'git-branch',
  'play', 'list-checks', 'target', 'graduation-cap', 'route', 'circle-dot', 'clock', 'star',
  'shield-check', 'workflow', 'rows-3', 'columns-3', 'file-code', 'plug', 'key', 'filter',
  'calendar', 'message-square', 'quote', 'book-marked', 'boxes', 'package-open', 'database-zap',
  'file-json', 'server', 'cog', 'git-pull-request', 'circle-play', 'chart-column', 'waypoints',
  'network', 'split', 'merge', 'timer', 'git-merge', 'circle-x', 'lock', 'eye', 'sigma',
  'percent', 'wand-sparkles', 'microscope', 'git-compare', 'file-check', 'table-properties',
  'braces', 'binary', 'scan-line', 'list-tree', 'folder-tree', 'square-stack', 'component',
  'pickaxe', 'trophy', 'medal', 'award',
];
let sprite = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n';
let missing = [];
for (const name of ICONS) {
  const src = path.join(nm, 'lucide-static/icons', `${name}.svg`);
  if (!fs.existsSync(src)) { missing.push(name); continue; }
  let raw = fs.readFileSync(src, 'utf8');
  const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').trim();
  sprite += `<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>\n`;
}
sprite += '</svg>\n';
const imgDir = path.join(root, 'assets/img');
ensure(imgDir);
fs.writeFileSync(path.join(imgDir, 'icons.svg'), sprite);
if (missing.length) console.warn('missing lucide icons:', missing.join(', '));

console.log(`vendored: ${families.reduce((s, f) => s + f.weights.length, 0)} font files, prism bundle, ${ICONS.length - missing.length} icons`);
